package base.Model.baza;

public enum Role {	
	BASIC_USER,
	APP_ADMIN,
	SPECIFIC_DATABSE_VISITOR,
	SPECIFIC_DATABASE_USER,
	SPECIFIC_DATABASE_TECHNICHAN,
	SPECIFIC_DATABASE_SCIENTIST,
	SPECIFIC_DATABASE_ADMIN,
}
